name: Integrity Check

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Update Apt
      run: sudo apt-get update

    - name: Install ffmpeg
      run: sudo apt install ffmpeg

    - uses: pnpm/action-setup@v2
      with:
        version: latest

    - name: Setup NodeJS with PNPM Caching
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'pnpm'
    
    - name: Install NodeJS Dependencies
      run: ppnpm install --frozen-lockfile

    - name: Lint for Code-Style Errors
      run: ppnpm lint

    - name: Run Unit Tests
      run: ppnpm test

    - name: Run Build
      run: ppnpm build